### ISSUE TITLE
Remove all icons from menu

### ISSUE THREAD

**Issue by samurailostinjapan** [ice-wm/icewm#25]
Hi

I have installed icewm and don't want to have any icons on the start menu or right click menu.

I removed all references to icons locations in the preference file under the icon path and I removed the icons from the icewm/icons folder and this removed most of the icons from the menu.
However icewm is still picking up icons from other installed icons themes that I will use for thunar/systray purposes.
![1](https://user-images.githubusercontent.com/10843832/92358203-1f08ab80-f124-11ea-8c19-a943c2882e44.png)

If I remove all icons-themes, then the menu has no icons, but once I install the icons again the menu has icons again.

This is what I want the menu to look like:
![2](https://user-images.githubusercontent.com/10843832/92358346-537c6780-f124-11ea-94a9-e9bd3958806c.png)
 

Can you tell me what is the proper way to remove all icons from the menus?
@arcolinuxz

**Comment by gijsbers** [comment]
Hello Dear Samurai,
A lot of work went into the 1.8.0 release to improve icon loading
and make IceWM more picturesque, so to say.
The no-menu-icons question never crossed our minds.
There are already so many icon-less window managers out there.
Just use them instead of IceWM.
BTW, who is your favorite samurai? Did you study his Dokkodo?
If you dedicate yourself to following his 21 precepts, you might no longer be lost.

**Comment by samurailostinjapan** [comment]
Thank you for your response!
Happy to let you know that we released ICEWM as our 19th desktop!

![icewm](https://user-images.githubusercontent.com/10843832/93001500-618a1800-f56a-11ea-817c-0400da1662e9.jpg)


If you are interested you can download it from here
https://bike.seedhost.eu/arcolinux/iso/arcolinuxb-icewm-v20.9.2.iso
