### ISSUE TITLE
Regression from 1.8.3: Alt-Enter does not restore original xterm window size

### ISSUE THREAD

**Issue by danfe** [ice-wm/icewm#28]
I typically run my xterms at 80x{something} for extra verticality, but occasionally need to temporarily maximize them to full screen with Alt-Enter (helps for e.g. reading the build logs and other texts with very long lines).

After I'm done, I press Alt-Enter again so the window size gets back to its original 80x{something}, which had been working fine until up to version 1.8.3.  With 1.9.0 and 1.9.1, it's now broken: the restored window has tiny size, you mostly see just the window decorations.

**Comment by danfe** [comment]
Thanks, but I'm afraid this is not enough to fully restore correct behavior.  After applying the patch, at first it looks like that correct geometry is restored, but if you try to press Alt-Enter several times, you'd notice that it's becoming wrong.  Just press and hold Alt-Enter and observe how xterm window slowly grows in both directions, in constrast with 1.8.3.

**Comment by gijsbers** [comment]
You need the complete set of fixes. See bbidulock/icewm#512.

**Comment by danfe** [comment]
> You need the complete set of fixes.

I've applied patches for 8b9cbcd and e3dc92c on top of the 1.9.1, this is not enough to fix the bug.  It's hard to reason about these changes as they are quite massive.  I'll try to bisect changes between 1.8.3 and 1.9.0 to try to find the commit which had broken this.

**Comment by danfe** [comment]
It got broken with 365f66b, just for the record.

**Comment by gijsbers** [comment]
That is the commit which gives a tiny sized xterm after restoring from fullscreen.
That has been fixed by commit 0a28669.
The slow growing has been fixed by commit e3dc92c, which has been confirmed by zaza42.
I'm not aware of any remaining bug to be fixed. If you disagree, please give detailed explanation.
One way is to give the output of `icesh spy` on your xterm. You could also give a screencast.
But note that the output of `icewm -V` must be 1.9.1.8.
What may also be helpful is if you have specific xterm resources, like fonts, border or terminal size.

**Comment by danfe** [comment]
> I'm not aware of any remaining bug to be fixed. If you disagree, please give detailed explanation.

I've just tested version 1.9.2 and looks like it's fixed, thank you!
