### ISSUE TITLE
Tab left border shadow ALT TAB switcher conflict

### ISSUE THREAD

**Issue by jidanni** [ice-wm/icewm#67]
I have discovered a rather serious problem with ALT TAB.

Here we are hitting ALT TAB, ALT TAB, ALT TAB...

**Keep your eyes on the row of tabs at the bottom**, *not the stack of
tabs in the middle.*

For people looking at the stack of tabs in the middle, all works
correctly.

For people looking at the row of tabs at the bottom, everything *seems*
to work correctly: the "pushed in" effect moves from one tab to another,
as we hit ALT TAB.

Wait: let's discuss what the "pushed in effect" is composed of:

1. Tab left border becomes black, indicating a shadow from a light
source to the right.
1. Tab color becomes darker.

OK, when does it fail? Well, when the tab color is darker in the first
place (E07:33macs tab). That was #61. Fine. Never mind that.

*BUT* the **left border shadow effect** then **also** breaks in this
case. **B U G.**

The left border shadow effect should keep on working, as it has nothing to do with entire tab color. Alas, it "takes a lunch break" with no good reason when encountering a shaded tab.

![20211029T075622](https://user-images.githubusercontent.com/1230959/139352720-32060a06-3997-42ee-b54a-a87b3383218e.jpg)

Anyway, users with eyes fixed on the bottom row, will on average hit up to 20 ALT TABs, waiting for the shadow effect to reach the tab they want. In fact it has already reached it several times. Then the user will realize he is being sent on a wild goose chase, and starts looking around for other hints of when he reaches the right tab to release ALT TAB on.

**Comment by gijsbers** [comment]
You can use a different theme, or edit the theme colors yourself.

**Comment by jidanni** [comment]
So it is a bug in the theme!

**Comment by gijsbers** [comment]
So? And? Software has about 15 bugs per 1000 lines of code.
Since this project delivers about 70000 lines of code to you,
it can be expected there will be at least 1000 bugs in it.
If it requires one hour to fix one bug then it would take five years
to fix them all. Is that what you expect me to do?
You only contribute a very large number of useless issues,
repeatedly reporting non-bugs or the same bugs in multiple issues.
All just wasting someone's time. Please go use a different window manager.
